### ISSUE TITLE
As a dev, I need to fix the way to choose the register url

### ISSUE THREAD

**Issue by tmodoux** [pryv/app-web-access#3]
For now, we can set register url by providing it inside url. But there is an edge-case: how to remember register url when using popup and return url?

Current method is using ?pryv-reg= inside url but this seems to interfer with other url parameters (&token...)

See: https://github.com/pryv/app-web-access/blob/feature/dev-options/js/script.js#L19

See: https://github.com/pryv/app-web-auth/blob/feature/v2/src/js/access/methods.js#L218

Priority: low, time: low

**Comment by kschiess** [comment]
@tmodoux Can you review this issue and judge if it is still a problem? And maybe close it if we covered this with the recent rewrite here?

**Comment by tmodoux** [comment]
We still use 'pryv-reg' URL parameter but it's not a problem anymore with the rewrite of app-web-auth.
